--
-- VHDL Test Bench CAD_lib.lab2_counter_tb.lab2_counter_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 20:41:46 02/14/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY lab2_counter_tb IS
   GENERIC (
      width : NATURAL RANGE 1 TO 64 := 8
   );
END lab2_counter_tb;


LIBRARY CAD_lib;
USE CAD_lib.ALL;


ARCHITECTURE rtl OF lab2_counter_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL D       : std_ulogic_vector(width - 1 DOWNTO 0);
   SIGNAL Inc_val : std_ulogic_vector(1 DOWNTO 0);
   SIGNAL Q       : std_ulogic_vector(width - 1 DOWNTO 0);
   SIGNAL Clock   : std_ulogic;
   SIGNAL enable  : std_ulogic;
   SIGNAL reset   : std_ulogic;


   -- Component declarations
   COMPONENT lab2_counter
      GENERIC (
         width : NATURAL RANGE 1 TO 64 := 8
      );
      PORT (
         D       : IN     std_ulogic_vector(width - 1 DOWNTO 0);
         Inc_val : IN     std_ulogic_vector(1 DOWNTO 0);
         Q       : OUT    std_ulogic_vector(width - 1 DOWNTO 0);
         Clock   : IN     std_ulogic;
         enable  : IN     std_ulogic;
         reset   : IN     std_ulogic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : lab2_counter USE ENTITY CAD_lib.lab2_counter;
   -- pragma synthesis_on

BEGIN

         U_0 : lab2_counter
            GENERIC MAP (
               width => width
            )
            PORT MAP (
               D       => D,
               Inc_val => Inc_val,
               Q       => Q,
               Clock   => Clock,
               enable  => enable,
               reset   => reset
            );

always: process
begin
  D<="00000011";
  Inc_val<="11";
  enable<='1';
  
  reset<='1';
  Clock<='0'; wait for 100ns;
  Clock<='1'; wait for 100ns;
  
  reset<='0';
  enable<='0';
  Clock<='0'; wait for 100ns;
  enable<='1';
  Clock<='1'; wait for 100ns;
  
   enable<='0';
  Clock<='0'; wait for 100ns;
  enable<='1';
  Clock<='1'; wait for 100ns;
  
   enable<='0';
  Clock<='0'; wait for 100ns;
  enable<='1';
  Clock<='1'; wait for 100ns;
  
  
 -- Clock<='0'; wait for 100ns;
--  Clock<='1'; wait for 100ns;
--  
--  Clock<='0'; wait for 100ns;
--  Clock<='1'; wait for 100ns;
--  
--  
--  reset<='1';
--
--  Clock<='0'; wait for 100ns;
--  Clock<='1'; wait for 100ns;
--   reset<='0';
--  Clock<='0'; wait for 100ns;
--  Clock<='1'; wait for 100ns;
--  
--  Clock<='0'; wait for 100ns;
--  Clock<='1'; wait for 100ns;
--  
 wait;
  
  
  
  
  
end process always;
END rtl;