--
-- VHDL Test Bench CAD_lib.lab3_fetch_tb.lab3_fetch_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 23:33:21 02/22/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY lab3_fetch_tb IS
   GENERIC (
      width : NATURAL RANGE 1 TO 64 := 32
   );
END lab3_fetch_tb;


LIBRARY CAD_lib;
USE CAD_lib.ALL;


ARCHITECTURE rtl OF lab3_fetch_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Jaddr : std_ulogic_vector(31 downto 0);
   SIGNAL Mdata : std_ulogic_vector(31 downto 0);
   SIGNAL clk   : std_ulogic;
   SIGNAL Jmp   : std_ulogic;
   SIGNAL Reset : std_ulogic;
   SIGNAL Delay : std_ulogic;
   SIGNAL Addr  : std_ulogic_vector(31 downto 0);
   SIGNAL Inst  : std_ulogic_vector(31 downto 0);
   SIGNAL Read  : std_ulogic;
   
   --signal inter : std_ulogic_vector(31 downto 0);

   -- Component declarations
   COMPONENT lab3_fetch
      GENERIC (
         width : NATURAL RANGE 1 TO 64 := 32
      );
      PORT (
         Jaddr : IN     std_ulogic_vector(31 downto 0);
         Mdata : IN     std_ulogic_vector(31 downto 0);
         clk   : IN     std_ulogic;
         Jmp   : IN     std_ulogic;
         Reset : IN     std_ulogic;
         Delay : IN     std_ulogic;
         Addr  : OUT    std_ulogic_vector(31 downto 0);
         Inst  : OUT    std_ulogic_vector(31 downto 0);
         Read  : OUT    std_ulogic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : lab3_fetch USE ENTITY CAD_lib.lab3_fetch;
   -- pragma synthesis_on

BEGIN

         U_0 : lab3_fetch
            GENERIC MAP (
               width => width
            )
            PORT MAP (
               Jaddr => Jaddr,
               Mdata => Mdata,
               clk   => clk,
               Jmp   => Jmp,
               Reset => Reset,
               Delay => Delay,
               Addr  => Addr,
               Inst  => Inst,
               Read  => Read
            );


process
begin
  
   Jaddr<=(others=>'0'); Jaddr(2)<='1';
  Mdata<=(others=>'0'); Mdata(2)<='1';
  
  -- test reset
  Reset<='0';Jmp <='0';Delay<='0';
  clk<='1'; wait for 100ns; 
  clk<='0'; wait for 100ns;
  
  Reset<='1';  Delay<='1';
  clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
 
  Reset<='1';  Delay<='0';
  clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
  
  Reset<='0';  Delay<='0';
  clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
  
   clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
  
   clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns; 
   -- test jmp
  Reset<='0'; 
  
 
  Jmp<='1';Delay<='1';
  clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
  
  
  Jmp<='1';
  clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
  
  Jmp<='0';Delay<='0';
  clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
  
  --test Delay
  
  clk<='1';wait for 100ns;
  Delay<='1';
  clk<='0'; wait for 100ns;
  
  
 
  clk<='1';wait for 100ns;
  clk<='0'; wait for 100ns;
  
  
  clk<='1'; wait for 100ns;
  Delay<='0';
  clk<='0';wait for 100ns;
  
  
  
  
  
  Jmp<='1'; 
  clk<='1';wait for 100ns;
  
  clk<='0'; wait for 100ns;
  
  --test risingk
  
  clk<='1';wait for 100ns;
  Jmp<='0';
  clk<='0'; wait for 100ns;
  
  clk<='1'; wait for 100ns;
  Jmp<='1';
  clk<='0';wait for 100ns;
  
wait;

end process;


END rtl;