--
-- VHDL Test Bench CAD_lib.lab3_fetch_unit_tb.lab3_fetch_unit_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 19:09:27 02/22/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE std.textio.all;

ENTITY lab3_fetch_unit_tb IS
   GENERIC (
      width : NATURAL RANGE 1 TO 64 := 32
   );
END lab3_fetch_unit_tb;


LIBRARY CAD_lib;
USE CAD_lib.ALL;


ARCHITECTURE rtl OF lab3_fetch_unit_tb IS

   -- Architecture declarations
  FILE test_vectors : text OPEN read_mode IS "vec.txt";
   -- Internal signal declarations
   SIGNAL Jaddr : std_ulogic_vector(31 downto 0);
   SIGNAL Mdata : std_ulogic_vector(31 downto 0);
   SIGNAL clk   : std_ulogic;
   SIGNAL Jmp   : std_ulogic;
   SIGNAL Reset : std_ulogic;
   SIGNAL Delay : std_ulogic;
   SIGNAL Addr  : std_ulogic_vector(31 downto 0);
   SIGNAL Inst  : std_ulogic_vector(31 downto 0);
   SIGNAL Read  : std_ulogic;


   -- Component declarations
   COMPONENT lab3_fetch_unit
      GENERIC (
         width : NATURAL RANGE 1 TO 64 := 32
      );
      PORT (
         Jaddr : IN     std_ulogic_vector(31 downto 0);
         Mdata : IN     std_ulogic_vector(31 downto 0);
         clk   : IN     std_ulogic;
         Jmp   : IN     std_ulogic;
         Reset : IN     std_ulogic;
         Delay : IN     std_ulogic;
         Addr  : OUT    std_ulogic_vector(31 downto 0);
         Inst  : OUT    std_ulogic_vector(31 downto 0);
         R_ead  : OUT    std_ulogic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : lab3_fetch_unit USE ENTITY CAD_lib.lab3_fetch_unit;
   -- pragma synthesis_on

BEGIN

         U_0 : lab3_fetch_unit
            GENERIC MAP (
               width => width
            )
            PORT MAP (
               Jaddr => Jaddr,
               Mdata => Mdata,
               clk   => clk,
               Jmp   => Jmp,
               Reset => Reset,
               Delay => Delay,
               Addr  => Addr,
               Inst  => Inst,
               Read  => Read
            );

stim : process

    VARIABLE L : LINE;
    variable v_clk,v_Reset,v_Jmp,v_Delay :std_ulogic;
begin 
    readline(test_vectors,L);
    
    WHILE NOT endfile(test_vectors) LOOP
      readline(test_vectors,L);
      read(L,v_clk); clk<=v_clk;
      read(L,v_Reset); Reset<=v_Reset;
      read(L,v_Jmp);Jmp<=v_Jmp;
      read(L,v_Delay);Delay<=v_Delay;
      wait for 100ns;
  END LOOP;
    report "END of TB";
      

 
end process;



--process
--begin
--   Jaddr<=(others=>'0'); Jaddr(2)<='1';
--  Mdata<=(others=>'0'); Mdata(2)<='1';
--  
--  -- test reset
--  Reset<='0';Jmp <='0';Delay<='0';
--  clk<='1'; wait for 100ns; 
--  clk<='0'; wait for 100ns;
--  
--  Reset<='1';  Delay<='1';
--  clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
-- 
--  Reset<='1';  Delay<='0';
--  clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
--  
--  Reset<='0';  Delay<='0';
--  clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
--  
--   clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
--  
--   clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns; 
--   -- test jmp
--  Reset<='0'; 
--  
-- --7
--  Jmp<='1';Delay<='1';
--  clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
--  
--  
--  Jmp<='1';Delay<='0';
--  clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
--  --9
--  Jmp<='0';
--  clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
--  
--  --test Delay
--  --10
--  clk<='1';wait for 100ns;
--  Delay<='1';
--  clk<='0'; wait for 100ns;
--  
--  --11
-- 
--  clk<='1';wait for 100ns;
--  clk<='0'; wait for 100ns;
--  
--  --12
--  clk<='1'; wait for 100ns;
--  Delay<='0';
--  clk<='0';wait for 100ns;
--  
--  
--  
--  --13
--  
--  Jmp<='1'; 
--  clk<='1';wait for 100ns;
--  
--  clk<='0'; wait for 100ns;
--  --14
--  --test risingk
--  
--  clk<='1';wait for 100ns;
--  Jmp<='0';
--  clk<='0'; wait for 100ns;
--  --15
--  clk<='1'; wait for 100ns;
--  Jmp<='1';
--  clk<='0';wait for 100ns;
--
--wait;
  
  
--end process;


END rtl;