--
-- VHDL Test Bench CAD_lib.lab9_reg_tracker_tb.lab9_reg_tracker_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 03:28:31 04/10/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY CAD_lib;
USE CAD_lib.RV32I.ALL;
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE std.textio.all;

ENTITY lab9_reg_tracker_tb IS
END lab9_reg_tracker_tb;


LIBRARY CAD_lib;
USE CAD_lib.ALL;


ARCHITECTURE rtl OF lab9_reg_tracker_tb IS

   -- Architecture declarations
FILE test_vectors : text OPEN read_mode IS "lab9_track_vec.txt";

   -- Internal signal declarations
   SIGNAL read1            : std_ulogic_vector(4 DOWNTO 0);
   SIGNAL read2            : std_ulogic_vector(4 DOWNTO 0);
   SIGNAL write_from_dec   : std_ulogic_vector(4 DOWNTO 0);
   SIGNAL write_from_wback : std_ulogic_vector(4 DOWNTO 0);
   SIGNAL read1_valid      : std_ulogic;
   SIGNAL read2_valid      : std_ulogic;
   SIGNAL reserve          : std_ulogic;
   SIGNAL free             : std_ulogic;
   SIGNAL clk              : std_ulogic;
   SIGNAL stall,stall_valid: std_ulogic;
   SIGNAL vecno : NATURAL := 0;

   -- Component declarations
   COMPONENT lab9_reg_tracker
      PORT (
         read1            : IN     std_ulogic_vector(4 DOWNTO 0);
         read2            : IN     std_ulogic_vector(4 DOWNTO 0);
         write_from_dec   : IN     std_ulogic_vector(4 DOWNTO 0);
         write_from_wback : IN     std_ulogic_vector(4 DOWNTO 0);
         read1_valid      : IN     std_ulogic;
         read2_valid      : IN     std_ulogic;
         reserve          : IN     std_ulogic;
         free             : IN     std_ulogic;
         clk              : IN     std_ulogic;
         stall            : OUT    std_ulogic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : lab9_reg_tracker USE ENTITY CAD_lib.lab9_reg_tracker;
   -- pragma synthesis_on

BEGIN

         U_0 : lab9_reg_tracker
            PORT MAP (
               read1            => read1,
               read2            => read2,
               write_from_dec   => write_from_dec,
               write_from_wback => write_from_wback,
               read1_valid      => read1_valid,
               read2_valid      => read2_valid,
               reserve          => reserve,
               free             => free,
               clk              => clk,
               stall            => stall
            );
			
sim: process
	VARIABLE L : LINE;

	variable vread1,vread2,vwrite_from_dec,vwrite_from_wback : std_ulogic_vector(4 DOWNTO 0);
	variable vread1_valid,vread2_valid,vreserve,vfree,vstall_valid :std_ulogic;
           
begin
	readline(test_vectors,L);
	
	WHILE NOT endfile(test_vectors) LOOP
    
    readline(test_vectors,L); 
	read(L,vread1); read1<=vread1;
	read(L,vread2); read2<=vread2;
	
	read(L,vwrite_from_dec); write_from_dec<=vwrite_from_dec;
	read(L,vwrite_from_wback); write_from_wback<=vwrite_from_wback;
	
	read(L,vread1_valid);	read1_valid<=vread1_valid;
	read(L,vread2_valid);	read2_valid<=vread2_valid;
	read(L,vreserve);		reserve<=vreserve;
	read(L,vfree);			free<=vfree;
	clk<='0'; wait for 100ns;
	
	read(L,vstall_valid);			stall_valid<=vstall_valid;
	clk<='1'; wait for 100ns;
	

	End Loop;
  report "END of TB";
  wait;


end process;
	
check : process(clk)
begin
  if falling_edge(clk) then
        vecno <= vecno + 1;
        
        
        ASSERT stall=stall_valid
        REPORT "ERROR: stall " & to_string(vecno)
        SEVERITY WARNING; 
        
        
 end if;     
  
end process;

	
-- process
-- begin
   -- read1 <="00000";
   -- read2<="00000";
   -- write_from_dec<="00001";
   -- write_from_wback<="00000";
   -- read1_valid<='0';
   -- read2_valid<='0';
   -- reserve<='1';
   -- free<='0';
   -- clk  <='0'; wait for 100ns;
   -- clk <='1'; wait for 100ns;
   
   
   -- read1 <="00000";
   -- read2<="00011";
   -- write_from_dec<="00011";
   -- write_from_wback<="00001";
   -- read1_valid<='0';
   -- read2_valid<='1';
   -- reserve<='1';
   -- free<='1';
   -- clk  <='0'; wait for 100ns;
   -- clk <='1'; wait for 100ns;
   
   
   -- read1 <="00001";
   -- read2<="00011";
   -- write_from_dec<="00000";
   -- write_from_wback<="00000";
   -- read1_valid<='1';
   -- read2_valid<='1';
   -- reserve<='0';
   -- free<='0';
   -- clk  <='0'; wait for 100ns;
   -- clk <='1'; wait for 100ns;
   
   
   
   -- read1 <="00001";
   -- read2<="00011";
   -- write_from_dec<="00000";
   -- write_from_wback<="00011";
   -- read1_valid<='1';
   -- read2_valid<='1';
   -- reserve<='0';
   -- free<='1';
   -- clk  <='0'; wait for 100ns;
   -- clk <='1'; wait for 100ns;
  
  -- wait;
-- end process;

END rtl;