--
-- VHDL Test Bench CAD_lib.mem_tb.mem_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 05:15:38 02/22/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY mem_tb IS
   GENERIC (
      width : NATURAL RANGE 1 TO 64 := 32
   );
END mem_tb;


LIBRARY CAD_lib;
USE CAD_lib.ALL;


ARCHITECTURE rtl OF mem_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Addr  : std_ulogic_vector(width -1 downto 0);
   SIGNAL Read  : std_ulogic;
   SIGNAL clk   : std_ulogic;
   SIGNAL Mdata : std_ulogic_vector(width -1 downto 0);
   SIGNAL Delay : std_ulogic;


   -- Component declarations
   COMPONENT mem
      GENERIC (
         width : NATURAL RANGE 1 TO 64 := 32
      );
      PORT (
         Addr  : IN     std_ulogic_vector(width -1 downto 0);
         Read  : IN     std_ulogic;
         clk   : IN     std_ulogic;
         Mdata : OUT    std_ulogic_vector(width -1 downto 0);
         Delay : OUT    std_ulogic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : mem USE ENTITY CAD_lib.mem;
   -- pragma synthesis_on

BEGIN

         U_0 : mem
            GENERIC MAP (
               width => width
            )
            PORT MAP (
               Addr  => Addr,
               Read  => Read,
               clk   => clk,
               Mdata => Mdata,
               Delay => Delay
            );
process
begin
  Addr <=(others=>'1');
  Read <= '1';
  clk <= '0';
  wait for 100ns;
  
  clk <= '1';wait for 100ns;
  
  
   
  clk <= '0';wait for 100ns;
  clk <= '1';Read <= '0'; Addr <=(others=>'0');wait for 100ns;
  
  clk <= '0';Read <= '1';wait for 100ns;
  clk <= '1';wait for 100ns;
  
  
  
  
end process;

END rtl;