--
-- VHDL Test Bench CAD_lib.or_gate_tester.or_gate_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 12:37:36 02/24/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY or_gate_tester IS
   PORT (
      Din0 : OUT    std_ulogic;
      Din1 : OUT    std_ulogic;
      Dout : IN     std_ulogic
   );
END or_gate_tester;


LIBRARY CAD_lib;

ARCHITECTURE rtl OF or_gate_tester IS
   -- Architecture declarations
BEGIN
END rtl;
