--
-- VHDL Test Bench CAD_lib.or_gate_tb.or_gate_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 12:37:36 02/24/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY or_gate_tb IS
END or_gate_tb;


LIBRARY CAD_lib;
USE CAD_lib.ALL;


ARCHITECTURE rtl OF or_gate_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Din0 : std_ulogic;
   SIGNAL Din1 : std_ulogic;
   SIGNAL Dout : std_ulogic;


   -- Component declarations
   COMPONENT or_gate
      PORT (
         Din0 : IN     std_ulogic;
         Din1 : IN     std_ulogic;
         Dout : OUT    std_ulogic
      );
   END COMPONENT;

   COMPONENT or_gate_tester
      PORT (
         Din0 : OUT    std_ulogic;
         Din1 : OUT    std_ulogic;
         Dout : IN     std_ulogic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : or_gate USE ENTITY CAD_lib.or_gate;
   FOR U_1 : or_gate_tester USE ENTITY CAD_lib.or_gate_tester;
   -- pragma synthesis_on

BEGIN

         U_0 : or_gate
            PORT MAP (
               Din0 => Din0,
               Din1 => Din1,
               Dout => Dout
            );

         U_1 : or_gate_tester
            PORT MAP (
               Din0 => Din0,
               Din1 => Din1,
               Dout => Dout
            );


END rtl;