--
-- VHDL Test Bench CAD_lib.reg_tb.reg_tester
--
-- Created:
--          by - W.UNKNOWN (DESKTOP-86TQKQ1)
--          at - 03:05:34 02/13/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY reg_tb IS
   GENERIC (
      width : NATURAL RANGE 1 TO 64 := 8
   );
END reg_tb;


LIBRARY CAD_lib;
USE CAD_lib.ALL;


ARCHITECTURE rtl OF reg_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL D      : std_ulogic_vector(width - 1 DOWNTO 0);
   SIGNAL Q      : std_ulogic_vector(width - 1 DOWNTO 0);
   SIGNAL clk    : std_ulogic;
   SIGNAL enable : std_ulogic;
   SIGNAL reset  : std_ulogic;


   -- Component declarations
   COMPONENT reg
      GENERIC (
         width : NATURAL RANGE 1 TO 64 := 8
      );
      PORT (
         D      : IN     std_ulogic_vector(width - 1 DOWNTO 0);
         Q      : OUT    std_ulogic_vector(width - 1 DOWNTO 0);
         clk    : IN     std_ulogic;
         enable : IN     std_ulogic;
         reset  : IN     std_ulogic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : reg USE ENTITY CAD_lib.reg;
   -- pragma synthesis_on

BEGIN

         U_0 : reg
            GENERIC MAP (
               width => width
            )
            PORT MAP (
               D      => D,
               Q      => Q,
               clk    => clk,
               enable => enable,
               reset  => reset
            );

always:process
begin
  
  d<="00001111";
  reset <='0';
  enable<='0';
  clk<='0'; wait for 100ns; 
  clk<='1'; wait for 100ns;
  --
  
  d<="00001111";
  reset <='0';
  enable<='1';
  clk<='0'; wait for 100ns; 
  clk<='1'; wait for 100ns;
  --
  
   d<="11111111";
  reset <='0';
  enable<='0';
  clk<='0'; wait for 100ns; 
  clk<='1'; wait for 100ns;
  --
  
  
  d<="11111111";
  reset <='1';
  enable<='1';
  clk<='0'; wait for 100ns; 
  clk<='1'; wait for 100ns;
  --
  
  d<="11111111";
  reset <='1';
  enable<='0';
  clk<='0'; wait for 100ns; 
  clk<='1'; wait for 100ns;
  --
  
  d<="11111111";
  reset <='0';
  enable<='0';
  clk<='0'; wait for 100ns; 
  enable<='1';
  clk<='1'; wait for 100ns;
  
  enable<='0';
  clk<='0'; wait for 100ns; 
  enable<='1';
  clk<='1'; wait for 100ns;
  
  enable<='0';
  clk<='0'; wait for 100ns; 
  enable<='1';
  clk<='1'; wait for 100ns;
  wait;
  

end process always;
END rtl;